version: 2
updates:
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    groups:
      docker-minor:
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions-minor:
        update-types:
          - minor
          - patch

  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
    allow:
      - dependency-type: "all"
    groups:
      pip-version-updates:
        applies-to: version-updates
        dependency-type: development
      pip-security-updates:
        applies-to: security-updates
        dependency-type: production
