name: Repo Tagger
description: Create a git tag with provided input. Does nothing on failure.
author: Bruno Ciconelle

inputs:
  tag:
    description: Tag that shall be created.
    required: true

outputs:
  tag:
    description: Tag created. Only available if tag was actually created.
  sha:
    description: Commit sha of the created tag. Only available if it was actually created.

runs:
  using: docker
  image: Dockerfile
  env:
    INPUT_TAG: ${{ inputs.tag }}
