name: Lint Codebase

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read
  packages: read
  statuses: write

jobs:
  lint:
    name: Lint Codebase
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pre-commit & other dev dependencies
        run: pip install -r dev-requirements.txt

      - name: Lint Codebase
        run: pre-commit run --all-files --hook-stage=manual --show-diff-on-failure
